

##thymeleaf auto refresh
#spring.thymeleaf.enabled=true
#spring.thymeleaf.cache=false
#spring.thymeleaf.prefix=classpath:templates/
#spring.thymeleaf.suffix=.html
#spring.thymeleaf.mode=HTML5


# JSP
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  # oracle set
  #spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:oracle:thin:@${DB_HOST}:${DB_PORT}:xe
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  #mybatis mapping
mybatis:
  type-aliases-package: com.example.boot.mapper

  #mapper.xml location
  mapper-locations: /sqlmap/mapper/**/*.xml

  #??????
  #spring.main.allow-bean-definition-overriding=true

server:
  port: 8082