
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:oracle:thin:@${DB_HOST}:${DB_PORT}:xe
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

mybatis:
  type-aliases-package: com.example.boot.mapper
  mapper-locations: /sqlmap/**/*.xml

server:
  port: 8082